---
# handlers file for deploy_apache_web
- name: Restart apache CentOS serv
  service: name=httpd state=restarted
  when: ansible_os_family == "RedHat"
- name: Restart apache Ubuntu serv
  service: name=apache2 state=restarted
  when: ansible_os_family == "Debian"
